apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
    type: back-end
spec:
  template:
    metadata:
      name: spring-boot-app
      labels:
        app: spring-boot
        type: back-end
    spec:
      containers:
        - name: spring-boot-app
          image: "lhamaoka/spring-boot-app:1.0"
          imagePullPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
      type: back-end